---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ECPIN

<!-- badges: start -->
<!-- badges: end -->

The current project aims to automatically analyze environmental chemcials binding to proteins through the APNA method

## Installation

You can install the the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("huiUofT/ASMS_drug")
```

Step 1: loading packages
```{r, message=FALSE, warning=FALSE}
  rm(list=ls())
  library(xcms)
  library(ASMSdrug)
  library(devtools)
  library(xlsx)
  library(ChemmineR)
  library(rcdk)
  library(MassSpecWavelet)
  library(Rcpp)
  library(RcppArmadillo)
  library(isopat)
  library(readxl)
  library(ggplot2)
  library(tidyverse)
  library(dplyr)
  library(ggrepel)
  library(openxlsx)
  library(gtools)
  data(iso_list)
  
  #load the library
  Database<-read_excel("EAS_MS_LIB.xlsx")#This is the chemical library
  ppmshift<-0#ppm shift for positive 
  ppm<-3#ppm for database searching
  STD<-'STD'#the standard
  Control<-'MeOH'#the control of methanol
  Fold<-2 #the fold change cutoff for hit discovery
  Ionmode<-'positive'
  
  #'set up the path
  path<-getwd()
  setwd(path)
  
  ##split data according to chemical pools
  
```

Step 2: splitting to negative and positive spectra
```{r, include= FALSE}
  SplitSpectra('neg')#the first scan is 'pos' or 'neg'
```

Step 3: extracting peak features
```{r, message=FALSE, warning=FALSE}
  setwd(path)
  ASMSrun(Ionmode,STD,Control)
  print('All done!!')
```

